sudo: required
language: node_js
branches:
  only:
  - develop
  - master
  - even-faster-deploy
node_js:
- '0.12'
before_install:
- curl https://install.meteor.com | /bin/sh
- npm install -g npm@'>=2.13.5'
- mkdir -p node_modules
script:
- cd $TRAVIS_BUILD_DIR
- mkdir /tmp/build
- meteor build /tmp/build
before_deploy:
- mkdir /tmp/deploy
- sh $TRAVIS_BUILD_DIR/.travis/namefiles.sh
- sh $TRAVIS_BUILD_DIR/.travis/sandstorm.sh
deploy:
  - provider: s3
    access_key_id: "AKIAIKIA7H7D47KUHYCA"
    secret_access_key: $ACCESSKEY
    bucket: "rocketchatbuild"
    skip_cleanup: true
    local_dir: /tmp/deploy
    on:
      branch:
      - develop
      - master
      - even-faster-deploy
  - provider: releases
    api_key: "GITHUB OAUTH TOKEN"
    file: "FILE TO UPLOAD"
    skip_cleanup: true
    on:
      branch: master
      tags: true
after_deploy:
- sh $TRAVIS_BUILD_DIR/.travis/docker.sh
